require:
  - rubocop-ordered_methods
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  rubocop-ordered_methods:
    - config/default.yml
  rubocop-performance:
    - config/default.yml
  rubocop-rails:
    - config/default.yml
  rubocop-rspec:
    - config/default.yml
  standard:
    - config/base.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - script/**/*
    - vendor/**/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Rails/FilePath:
  EnforcedStyle: arguments

Rails/RakeEnvironment:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*

RSpec/Dialect:
  Enabled: true
  PreferredMethods:
    context: describe

RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
    - spec/support/shared_examples/company_controller.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

Style/FrozenStringLiteralComment:
  Enabled: false # TODO: Enable this!

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
