version: "3"

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: coyote_development
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  web: &rails
    build:
      context: .
      args:
        bundle_without: ""
    command: bundle exec rails server -b 0.0.0.0
    depends_on:
      - db
    environment:
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap
      DATABASE_HOST: db
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEB_CONCURRENCY: 1
    ports:
      - 3000:3000
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - .:/coyote:cached
      - bundle:/usr/local/bundle
      - node_modules:/coyote/node_modules
      - packs:/coyote/public/packs
      - rails_cache:/coyote/tmp/cache

  test:
    <<: *rails
    command: ./bin/docker_entrypoint bundle exec rails db:test:prepare db:migrate spec
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_HOST: db
      NODE_ENV: test
      RAILS_ENV: test
      WEB_CONCURRENCY: 1

volumes:
  bundle:
  node_modules:
  packs:
  postgres:
  rails_cache:
  redis:
