default: &default
  adapter: postgresql
  pool: <%= (ENV["DB_POOL_SIZE"] || ENV["THREADS"] || 5).to_i %>
  url: <%= Credentials.fetch(:database_url) { ENV["DATABASE_URL"] } %>

development:
  <<: *default
  database: coyote_development

test: &test
  <<: *default
  database: coyote_test

production:
  <<: *default
  database: coyote_production
  reconnect: true
